development:
  address: "smtp.gmail.com"
  port: "587"
  domain: "gmail.com"
  authentication: "plain"
  user_name: "zowie7912@gmail.com"
  password: "jack13929"
  enable_starttls_auto: true

production:
  address: "smtp.gmail.com"
  port: "587"
  domain: "gmail.com"
  authentication: "plain"
  user_name: "zowoe7912@gmail.com"
  password: "jack13929"
  enable_starttls_auto: true